### ISSUE TITLE
Usage doc

### ISSUE THREAD

**Issue by meysam81** [kamyar1979/bunny#1]
Hello Kamyar

I'm interested in your work & I would like to know how one can use what you built? There isn't clear documentation and just running `./bunny` wouldn't work.

Please guide me and others in how to run your application by adding proper documentation to your README file.

Thanks in advance.

**Comment by meysam81** [comment]
```
meysam@meysam-pc:bunny$ ls -l bunny 
-rwxr-xr-x 1 meysam meysam 13325552 Mar  5 11:36 bunny

meysam@meysam-pc:bunny$ ./bunny 
-bash: ./bunny: cannot execute binary file: Exec format error
```

**Comment by kamyar1979** [comment]
Which build are you using? Can you build the project yourself for your architecture?

**Comment by kamyar1979** [comment]
The usage is same as httpie:

./bunny http://dlang.org

./bunny POST https://mysite.com/login username=myuser password=mypassword

**Comment by meysam81** [comment]
I'm not using any build. I'm just trying to run the binary inside the repository.
And I also did try to compile it with `dmd` such as follow:
```bash
meysam@meysam-pc:bunny$ dmd src/app.d 
src/app.d(8): Error: module requests is in file 'requests.d' which cannot be read
import path[0] = /snap/dmd/102/bin/../import/druntime
import path[1] = /snap/dmd/102/bin/../import/phobos
src/app.d(11): Error: module colorize is in file 'colorize.d' which cannot be read
import path[0] = /snap/dmd/102/bin/../import/druntime
import path[1] = /snap/dmd/102/bin/../import/phobos
```

**Comment by kamyar1979** [comment]
Sorry! It is not the way D projects build! You have to use dub for dependencies:

dub build

**Comment by meysam81** [comment]
OK then, although I have to try it out, it might be a good idea for you to add this in the README as well. :pray:

**Comment by meysam81** [comment]
also:

```bash
meysam@meysam-pc:bunny$ dub build                                                                                                                                        
The dependency resolution process is taking too long. The dependency graph is likely hitting a pathological case in the resolution algorithm. Please file a bug report at 
https://github.com/dlang/dub/issues and mention the package recipe that reproduces this error.                                                                            
```

**Comment by kamyar1979** [comment]
Sorry! You are using Iran internet! You have to use http://shecan,ir, http://begzar.ir or use some VPN. There is no problem with the package.

**Comment by meysam81** [comment]
```bash
Root package bunny references unknown package requests:vibed
```
